version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{S3_BUCKET}}"
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build started on `date`
artifacts:
  files:
    - ./target/*
  discard-paths: yes
